baseURL = 'https://simple-rules-for-losing-weight.com/'
#theme = "ananke"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = "true"
enableRobotsTXT = true
SectionPagesMenu = "main"
Paginate = 9
pluralizelisttitles = false


[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'


[languages]
  [languages.en]
    languageCode= 'en-UK'
    languageName= 'English'
    contentDir = 'content/en'
    title= 'Simple Rules For Losing Weight'
    weight= 1
    [languages.en.params]
      read_more_copy= 'Read more'
      srflw_note = "Note: The writer is not a specialist or expert in the field, has no medical or sport-related qualifications and absolves himself of all responsibility and liability. Reader should use their own common sense and are solely responsible for trying out what they read on this website."

  [languages.hu]
    languageCode = 'hu-HU'
    contentDir = 'content/hu'
    languageName = 'Magyar'
    title = 'Egyszerű szabályok a fogyáshoz'
    weight = 2
    [languages.hu.params]
      srflw_note = "Megjegyzés: Az író nem szakember vagy szakértő a témában, nem rendelkezik orvosi vagy sporttal kapcsolatos képesítéssel, és minden felelősség és kötelezettség alól felmenti magát. Az olvasónak a saját józan ítélőképességét kell használnia, és egyedül az olvasó felelőssége, hogy kipróbálja amit ezen a weboldalon olvas."
      read_more_copy = 'Olvass tovább'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  myOldAge = 44
  myNewAge = 48
  myHeight = 170
  myOldWeight = 118
  myNewWeight = 67
  myOldOptimalBmi = 23
  myNewOptimalBmi = 21
  myOldCalorieDeficit = 0
  myOldActiveCalories = 2000
  myOldWeeklyWeightLoss = 0.5
#  text_color = ""
  author = "Barna Szeghy"
  favicon = "favicon.ico"
  site_logo = "/simple-rules-for-losing-weight-logo.svg"
  recent_posts_number = 6
  body_classes = "helvetica bg-near-white"
  env = "production"



[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/simple.rules.for.losing.weight"
[[params.ananke_socials]]
name = "Garmin"
url = "https://connect.garmin.com/modern/profile/UnbrownGorger"
color= '#12aded'
[[params.ananke_socials]]
name = "MyFitnessPal"
url = "https://www.myfitnesspal.com/profile/EnvaultRoll"
color= '#0066ee'
[[params.ananke_socials]]
name = "github"
url = "https://github.com/szeghybarna/srflw"
